// uScript uScript_Collision.cs
// (C) 2010 Detox Studios LLC
// Desc: Fires an event signal when Instance receives a collision.

using UnityEngine;
using System.Collections;


[AddComponentMenu("uScript/Event Components/Collision")]
[NodeComponentType(typeof(Collider), typeof(Rigidbody))]

[NodePath("Events/Physics Events")]
[NodeLicense("http://www.detoxstudios.com/legal/eula.html")]
[NodeCopyright("Copyright 2011 by Detox Studios LLC")]
[NodeToolTip("Fires an event signal when Instance receives a collision.")]
[NodeDescription("Fires an event signal when Instance receives a collision.\n \nRelative Velocity: The relative linear velocity of the two colliding objects.\nRigid Body: The Rigidbody of Instigator. This is null if the Instigator is a collider with no rigidbody attached.\nCollider: The collider of Instance.\nTransform: The transform of the Instigator.\nContact Points: The contact points generated by the physics engine.\nInstigator: The object that collided with Instance.")]
[NodeAuthor("Detox Studios LLC", "http://www.detoxstudios.com")]
[NodeHelp("http://www.uscript.net/docs/index.php?title=Node_Reference_Guide#On_Collision")]

[FriendlyName("On Collision")]
public class uScript_Collision : uScriptEvent
{
   public delegate void uScriptEventHandler(object sender, CollisionEventArgs args);

   public class CollisionEventArgs : System.EventArgs
   {
      private Collision m_Collision;

      [FriendlyName("Relative Velocity")]
      public Vector3 RelativeVelocity { get { return m_Collision.relativeVelocity; } }

      [FriendlyName("Rigid Body")]
      public Rigidbody RigidBody { get { return m_Collision.rigidbody; } }

      [FriendlyName("Collider")]
      public Collider Collider { get { return m_Collision.collider; } }

      [FriendlyName("Transform")]
      public Transform Transform { get { return m_Collision.transform; } }

      [FriendlyName("Contact Points")]
      public ContactPoint[] Contacts { get { return m_Collision.contacts; } }

      [FriendlyName("Instigator")]
      public GameObject GameObject { get { return m_Collision.gameObject; } }

      public CollisionEventArgs(Collision collision)
      {
         m_Collision = collision;
      }
   }

   [FriendlyName("On Collision Enter")]
   public event uScriptEventHandler OnEnterCollision;

   [FriendlyName("On Collision Exit")]
   public event uScriptEventHandler OnExitCollision;

   [FriendlyName("On Collision Stay")]
   public event uScriptEventHandler WhileInsideCollision;
 
   void OnCollisionEnter(Collision collision)
   {
      if ( OnEnterCollision != null ) OnEnterCollision( this, new CollisionEventArgs(collision) ); 
   }

   void OnCollisionExit(Collision collision)
   {
      if ( OnExitCollision != null ) OnExitCollision( this, new CollisionEventArgs(collision) ); 
   }

   void OnCollisionStay(Collision collision)
   {
      if ( WhileInsideCollision != null ) WhileInsideCollision( this, new CollisionEventArgs(collision) ); 
   }
}
